### ISSUE TITLE
Support 6.43+ authentication scheme

### ISSUE THREAD

**Issue by mhaebler** [jellonek/rosapi#11]
6.43 - currently in RC - changes the API authentication scheme. See https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

Are there any plans for supporting that?

**Comment by jellonek** [comment]
Didn't had that plan as this project is stale for few years, but...
Will implement that during the weekend.
Will prepare PR and ask you to review then.

**Comment by mhaebler** [comment]
I would suggest making the <=6.42 and >=6.43 process transparent to the end user. See dummy user approach in librouteros.

https://github.com/luqasz/librouteros/blob/master/librouteros/__init__.py#L26

**Comment by jellonek** [comment]
I've leaved that as a verbose option in #13 and #14.
